### ISSUE TITLE
Cursor and shadow issues in Firefox

### ISSUE THREAD

**Issue by jordanmkoncz** [mixinmax/jquery.swatches#5]
In Firefox, with the cursor positioned in between the name of the swatch and the swatch itself, the cursor will constantly switch between the default cursor and the cursor for when you're hovering over text. Also, the shadow around the swatch will repeatedly be shown and hidden.

**Comment by mixinmax** [comment]
Thanks for logging the issue @jordanmkoncz. I'll take a look at it tonight.

**Comment by mixinmax** [comment]
This is the same issue as #6 
Closing.
