### ISSUE TITLE
Demo site jquery.swatches.js not loading

### ISSUE THREAD

**Issue by tlongren** [mixinmax/jquery.swatches#7]
Not a major deal, just wanted to let you know jquery.swatches.js isn't loading on your demo site.

Here's what Chrome says:
Refused to execute script from 'https://raw.github.com/maxmackie/jquery.swatches/master/jquery.swatches.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Sorry if you'd rather not have this reported here on Github.

**Comment by mixinmax** [comment]
Weird, it works for me on Chrome. I do get that error though.
I'm trying to include the js right from the repo so I don't have to update the website every time there's a change made to the plugin. I'll fall back to a static file and find a solution later. Thanks for letting me know.

**Comment by tlongren** [comment]
Oh hell yah. Looks great now.

This may be of interest to you regarding including js from raw.github.com. 
https://plus.google.com/+MikeWest/posts/28f8HS2M7cb

and this:
http://rawgithub.com/

**Comment by mixinmax** [comment]
Oh cool, thanks for the links @tlongren, I'll look into it.
